name: Bug Report
description: Report a bug
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        This form is for the VSCode desktop extension, if you are using the browser extension open an issue [here](https://github.com/KatsuteDev/BackgroundX/issues/new/choose). <br><br>

  - type: markdown
    attributes:
      value: |
        Before opening a bug report please check that your issue was not already discussed in the following:

        * [Issues](https://github.com/KatsuteDev/Background/issues?q=is%3Aissue+is%3Aopen+label%3Abug%2C%22critical+bug%22)
        * [Common Issues](https://github.com/KatsuteDev/Background/blob/main/HELP.md)

        Please also check that:

        * This is actually a bug and not a feature.
        * You are running the latest extension version.

        If your VSCode is blank or stops working please check [here](https://github.com/KatsuteDev/Background#%EF%B8%8F-vscode-stopped-working) first.

  - type: input
    id: os
    attributes:
      label: Operating System
    validations:
      required: true

  - type: input
    id: vs
    attributes:
      label: VSCode Version
      description: |
        Include the [version](https://code.visualstudio.com/docs/supporting/FAQ#_how-do-i-find-the-version) and type.

        Do not write 'latest'
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Extension Version
      description: |
        Do not write 'latest'.
    validations:
      required: true

  - type: textarea
    id: settings
    attributes:
      label: Settings
      description: |
        Include `background.*` settings from the [settings.json](https://code.visualstudio.com/docs/getstarted/settings#_settingsjson) file.

        Make sure to remove any sensitive information.

  - type: textarea
    attributes:
      label: Issue
      description: |
        Explain the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to replicate
      description: |
        Include steps to reproduce this issue. Add a video if possible.
    validations:
      required: true