name: Bug Report
description: Report a bug
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report please check that your issue was not already discussed in the following:

        * [Issues](https://github.com/KatsuteDev/Background/issues?q=is%3Aissue+is%3Aopen+label%3Abug%2C%22critical+bug%22)
        * [Known Issues](https://github.com/KatsuteDev/Background#%EF%B8%8F-known-issues)

        Please also check that:

        * This is actually a bug and not a feature.
        * You are running the latest extension version.

        If you have are trying to change or remove a background please refer to [#52](https://github.com/KatsuteDev/Background/issues/52).

        If your VSCode is blank or stops working please check [here](https://github.com/KatsuteDev/Background#%EF%B8%8F-vscode-stopped-working) first.

  - type: input
    attributes:
      label: Operating System
    validations:
      required: true

  - type: input
    attributes:
      label: VSCode Version
      description: |
        Include the [version](https://code.visualstudio.com/docs/supporting/FAQ#_how-do-i-find-the-version) and type.
    validations:
      required: true

  - type: input
    attributes:
      label: Extension Version
      description: |
        Do not write 'latest'.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Issue
      description: |
        Explain the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Settings
      description: |
        Include `background.*` settings from the [settings.json](https://code.visualstudio.com/docs/getstarted/settings#_settingsjson) file. Remove any sensitive information.

  - type: textarea
    attributes:
      label: How to replicate
      description: |
        Include steps to reproduce this issue. Add a video if possible.
    validations:
      required: true