name: Feature Request
description: Suggest a new feature
labels: [feature request]
assignees: []
body:
  - type: markdown
    attributes:
      value: |-
        This form is for the VSCode desktop extension, if you are using the browser extension open an issue [here](https://github.com/KatsuteDev/BackgroundX/issues/new/choose). <br><br>

  - type: checkboxes
    attributes:
      label: Checks
      description: |-
        Save time and check the below before submitting a feature request, it may already have an answer:
      options:
        - label: I have checked [existing feature requests](https://github.com/KatsuteDev/Background/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22).
          required: true
        - label: This feature does not already exist.
          required: true
        - label: This is not a localization/translation request.
          required: true
        - label: I am using the latest extension version.
          required: true

  - type: checkboxes
    attributes:
      label: This is a Feature
      description: |-
        Do not use the feature request form to submit bugs, you must use the [bug report](https://github.com/KatsuteDev/Background/issues/new?template=bug.yml) form.
      options:
        - label: This is a feature request and not a bug report.
          required: true

  - type: textarea
    attributes:
      label: Feature
      description: |-
        Explain the feature.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reason
      description: |-
        Explain why you think this feature should be added.
    validations:
      required: true