name: Generate Badge
on:
  workflow_dispatch:
  schedule:
    - cron: 0 11 * 1-2,11-12 1
    - cron: 0 10 * 3-10 1

jobs:
  badge:
    name: Generate Badge
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          architecture: x64
          cache: npm
          node-version: 24

      - name: Generate
        run: node badge.js

      - name: Commit
        run: |-
          git config --global user.name "kdevbot[bot]"
          git config --global user.email "155479163+kdevbot[bot]@users.noreply.github.com"
          git add badge-*.svg
          git commit -m "Update badges"
          git push