name: Repository[bot]
on:
  workflow_dispatch: {}
  label:
    types: [created, edited, deleted]
  issues:
    types: [opened, closed, reopened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    branches: [main]
    types: [opened, closed, reopened, edited]
  release:
    types: [created, published]

jobs:
  repository-bot:
    name: Repository[bot]
    uses: Katsute/Workflows/.github/workflows/bot.yml@main
    if: >-
      ${{
      (github.repository_owner == 'Katsute' || github.repository_owner == 'KatsuteDev') &&
      github.actor != 'mashiro-san' &&
      !endsWith(github.actor, '[bot]')
      }}
    secrets:
      token: ${{ secrets.BOT }}