name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    uses: KatsuteDev/Workflows/.github/workflows/npm.deploy.vs.yml@main
    with:
      file: '**.vsix'
      environment: VSCE Package
    secrets: inherit