name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    uses: Katsute/Workflows/.github/workflows/npm.vsce.deploy.yml@main
    with:
      file: '*.vsix'
      environment: VSCE Package
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      VSCE: ${{ secrets.VSCE }}