name: kdevbot[bot]
on:
  workflow_dispatch:
  schedule:
    - cron: 0 11 * 1-2,11-12 1
    - cron: 0 10 * 3-10 1
  create:
  issues:
    types: [opened, reopened, closed]
  pull_request:
    branches: [main]
    types: [opened, reopened, closed]
  issue_comment:
    types: [created]
  release:
    types: [published]

jobs:
  kdevbot:
    name: kdevbot[bot]
    uses: KatsuteDev/kdevbot/.github/workflows/kdevbot.yml@main
    if: >-
      github.repository_owner == 'KatsuteDev' &&
      !endsWith(github.actor, '[bot]')
    secrets: inherit