name: Test Main File

on: [workflow_dispatch, push]

jobs:
  test-windows:
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      shell: bash
      run: |-
        choco install wget -y
        choco install vscode -y

    - name: Install VSIX extension
      shell: bash
      run: |-
        cd 'C:\ProgramData\chocolatey\lib\vscode'
        code --install-extension test/test.vsix

    - name: Launch VS Code
      shell: bash
      run: |-
        cd 'C:\ProgramData\chocolatey\lib\vscode'
        code --verbose &
        sleep 15

    - name: Print Output
      shell: bash
      run: |-
        cat /c/Users/runneradmin/AppData/Local/Temp/test.txt >> $GITHUB_STEP_SUMMARY

  test-ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        shell: bash
        run: |-
          sudo apt-get update
          sudo apt-get install -y wget gpg
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
          sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
          sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
          sudo apt-get install -y apt-transport-https
          sudo apt-get update
          sudo apt-get install -y code
          sudo apt-get install -y xvfb

      - name: Install VSIX extension
        shell: bash
        run: |-
          code --install-extension test/test.vsix

      - name: Launch VS Code
        shell: bash
        run: |-
          cd /usr/share/code
          xvfb-run code --verbose &
          sleep 15

      - name: Print Output
        shell: bash
        run: |-
          cat /tmp/test.txt >> $GITHUB_STEP_SUMMARY

  test-macos:
    name: MacOS
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      shell: bash
      run: |-
        brew update
        brew install --cask visual-studio-code

    - name: Install VSIX extension
      shell: bash
      run: |-
        /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --install-extension test/test.vsix

    - name: Launch VS Code
      shell: bash
      run: |-
        /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --verbose &
        sleep 15

    - name: Print Output
      shell: bash
      run: |-
        sleep 1
        cat $(echo $TMPDIR)test.txt >> $GITHUB_STEP_SUMMARY