name: Test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: Test
    timeout-minutes: 2
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Create File
        shell: bash
        run: |
          echo "A" > A.txt
          echo "B" > B.txt

      - name: Copy (Windows)
        if: matrix.os == 'windows-latest'
        run: xcopy /r /y "A.txt" "C.txt*"; xcopy /r /y "B.txt" "D.txt*"

      - name: Copy (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo sh -c "cp -f 'A.txt' 'C.txt'; cp -f 'B.txt' 'D.txt'"

      - name: Copy (Mac)
        if: matrix.os == 'macos-latest'
        run: sudo sh -c "cp -f 'A.txt' 'C.txt'; cp -f 'B.txt' 'D.txt'"

      - name: List Files
        shell: bash
        run: ls

      - name: Script
        uses: actions/github-script@v6
        with:
          script: |
            const platform = process.platform;

            const cp = (files, asterisk = false) => {
                let commands = [];
                for(const file of files)
                    commands.push(platform == "win32"
                        ? `xcopy /r /y "${file[0]}" "${file[1]}${asterisk ? '*' : ''}"`
                        : `cp -f '${file[0]}' '${file[1]}'`);
                if(platform == "win32")
                    return commands.join(" && ");
                else if(platform == "darwin")
                    return `sh -c "${commands.join("; ")}"`;
                else
                    return commands.join("; ");
            };

            console.log(cp([["A.txt", "C.txt"], ["B.txt", "D.txt"]]));
            console.log(cp([["A.txt", "C.txt"], ["B.txt", "D.txt"]], true));