name: Test MacOS

on: [workflow_dispatch]

jobs:
  test-macos:
    name: Test MacOS
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      shell: bash
      run: |-
        brew update
        brew install --cask visual-studio-code

    - name: Install VSIX extension
      shell: bash
      run: |-
        /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --install-extension test/test.vsix
        sleep 5

    - name: Launch VS Code
      shell: bash
      run: |-
        /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --verbose &
        sleep 20

    - name: Print Output
      shell: bash
      run: |-
        ls $TMPDIR
        sleep 1
        echo ======
        sleep 1
        cat $(echo $TMPDIR)test.txt