name: Test Ubuntu

on: [workflow_dispatch, push]

jobs:
  test-ubuntu:
    name: Test Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |-
        sudo apt-get update
        sudo apt-get install -y wget gpg

    - name: Install Visual Studio Code
      run: |-
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
        sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
        sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
        sudo apt-get install -y apt-transport-https
        sudo apt-get update
        sudo apt-get install -y code

    - name: Install VSIX extension
      run: |-
        code --install-extension test/test.vsix
        sleep 10

    - name: Launch VS Code
      run: |-
        code &
        sleep 20
        ls /var/tmp
        sleep 1
        ls /tmp
        cat /var/tmp/test.txt
        exit 0