name: Test MacOS

on: [workflow_dispatch, push]

jobs:
  test-macos:
    name: Test MacOS
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      shell: bash
      run: |-
        brew update
        brew install --cask visual-studio-code

    - name: Install VSIX extension
      shell: bash
      run: |-
        /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --install-extension test/test-macos.vsix
        sleep 5

    - name: Launch VS Code
      shell: bash
      run: |-
        open -a "Visual Studio Code" --args --verbose &
        sleep 20

    - name: Print Output
      shell: bash
      run: |-
        ls /tmp
        sleep 1
        echo ======
        sleep 1
        cat /tmp/test.txt